// Participations membre <-> projet — source de vérité : export DB (backup_site_vitrine_28-07-2026.sql).
// Régénéré le 2026-07-28. Résolu par slug de membre + clé naturelle de projet
// (name, year, category), car les IDs auto-incrémentés ne sont pas stables
// d'un environnement à l'autre.

export type ParticipationRow = {
  memberSlug: string;
  projectName: string;
  projectYear: number;
  projectCategory: "LEGAL" | "ILLEGAL";
  structure: string;
  grade: string | null;
  order: number;
};

export const PARTICIPATIONS: ParticipationRow[] = [
  { memberSlug: "anas36", projectName: "American Dream", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Chief of Police", order: 0 },
  { memberSlug: "anas36", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Governor of San Andreas", order: 0 },
  { memberSlug: "anas36", projectName: "AMI RP", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Co-lead", order: 0 },
  { memberSlug: "anas36", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sheriff", order: 0 },
  { memberSlug: "anas36", projectName: "Aria Life V1", projectYear: 2021, projectCategory: "ILLEGAL", structure: "Famille Italienne De Luca", grade: "Membre", order: 0 },
  { memberSlug: "anas36", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: "Comissionner", order: 0 },
  { memberSlug: "anas36", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "ILLEGAL", structure: "Famille Texane Ross", grade: "Lead", order: 0 },
  { memberSlug: "anas36", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sheriff", order: 0 },
  { memberSlug: "anas36", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Director", order: 0 },
  { memberSlug: "anas36", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Bloods", grade: "Membre", order: 0 },
  { memberSlug: "anas36", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Emissaire", order: 0 },
  { memberSlug: "anas36", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Clan Genna", grade: "Co-lead", order: 0 },
  { memberSlug: "anas36", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Cayo Perico", grade: "Presidente", order: 0 },
  { memberSlug: "anas36", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Co-lead", order: 0 },
  { memberSlug: "anas36", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Jefe", order: 0 },
  { memberSlug: "anas36", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Capitaine", order: 0 },
  { memberSlug: "anas36", projectName: "Initiale", projectYear: 2021, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Commandant-Adjoint", order: 0 },
  { memberSlug: "anas36", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Comandante", order: 0 },
  { memberSlug: "anas36", projectName: "MetaRP Whitelist", projectYear: 2022, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "anas36", projectName: "MetaRP Whitelist", projectYear: 2022, projectCategory: "ILLEGAL", structure: "Sons of Anarchy MC", grade: "Président", order: 0 },
  { memberSlug: "anas36", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: "Jefe", order: 0 },
  { memberSlug: "anas36", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sheriff", order: 0 },
  { memberSlug: "anas36", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Chief of Police", order: 0 },
  { memberSlug: "anas36", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Chief of Police", order: 0 },
  { memberSlug: "anas36", projectName: "Origin RP", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Famille Texane Duggan", grade: "Fraterie Duggan", order: 0 },
  { memberSlug: "anas36", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Director", order: 0 },
  { memberSlug: "anas36", projectName: "SLife", projectYear: 2021, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Capitaine", order: 0 },
  { memberSlug: "anas36", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Governor of San Andreas", order: 0 },
  { memberSlug: "anas36", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Director", order: 0 },
  { memberSlug: "anas36", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Director", order: 0 },
  { memberSlug: "anas36", projectName: "ViceLand", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "anas36", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Chief Operating Officer", order: 0 },
  { memberSlug: "tom-los", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Lieutenant Governor", order: 0 },
  { memberSlug: "tom-los", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "tom-los", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Special Advisor", order: 0 },
  { memberSlug: "tom-los", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "tom-los", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "tom-los", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "tom-los", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "anas36", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Director", order: 0 },
  { memberSlug: "tom-los", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Soldat du SD", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "anas36", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Chief of Police", order: 0 },
  { memberSlug: "thedarkwolf", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "ldr", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "ldr", projectName: "Anesya", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Groupe Rokossovski", grade: "Lead", order: 0 },
  { memberSlug: "ldr", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "ldr", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "ldr", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Grande Jefe", order: 0 },
  { memberSlug: "ldr", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Cayo Perico", grade: "Presidente", order: 0 },
  { memberSlug: "ldr", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Lead", order: 0 },
  { memberSlug: "ldr", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "ldr", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Lieutenant Governor", order: 0 },
  { memberSlug: "ldr", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Captain", order: 0 },
  { memberSlug: "ldr", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Captain", order: 0 },
  { memberSlug: "ldr", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "ldr", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "ldr", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Capitan", order: 0 },
  { memberSlug: "ldr", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "ldr", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "ldr", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Detective", order: 0 },
  { memberSlug: "flyzz", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "flyzz", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "flyzz", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Cayo Perico", grade: "Ministro", order: 0 },
  { memberSlug: "flyzz", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "flyzz", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "flyzz", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: "Special Agent", order: 0 },
  { memberSlug: "flyzz", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "flyzz", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "flyzz", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "flyzz", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "flyzz", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "flyzz", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "flyzz", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "kaizz", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "kaizz", projectName: "AMI RP", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "kaizz", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Agent de sécurité", order: 0 },
  { memberSlug: "kaizz", projectName: "ViceLand", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "kaizz", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "kaizz", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "kaizz", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "kaizz", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Chief of Staff", order: 0 },
  { memberSlug: "kaizz", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "kaizz", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "kaizz", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "kaizz", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "kaizz", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "kaizz", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Emissaire", order: 0 },
  { memberSlug: "kaizz", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: "Membre", order: 0 },
  { memberSlug: "flyzz", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: "Membre", order: 0 },
  { memberSlug: "ldr", projectName: "FRAME", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Hustle Nation 74", grade: null, order: 0 },
  { memberSlug: "ldr", projectName: "FRAME", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Famille Ramirez", grade: null, order: 0 },
  { memberSlug: "ldr", projectName: "Hurricane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Clan des Kazakh", grade: null, order: 0 },
  { memberSlug: "anas36", projectName: "SunLight", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Indépendants", grade: null, order: 0 },
  { memberSlug: "idriss-brk", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "idriss-brk", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Soldat du SD", order: 0 },
  { memberSlug: "idriss-brk", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Avocat du gouvernement", order: 0 },
  { memberSlug: "idriss-brk", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "idriss-brk", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "idriss-brk", projectName: "Hurricane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Clan des Kazakh", grade: null, order: 0 },
  { memberSlug: "idriss-brk", projectName: "FRAME", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Famille Ramirez", grade: null, order: 0 },
  { memberSlug: "idriss-brk", projectName: "FRAME", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Hustle Nation 74", grade: null, order: 0 },
  { memberSlug: "idriss-brk", projectName: "SLife", projectYear: 2021, projectCategory: "ILLEGAL", structure: "Mafia Russe", grade: null, order: 0 },
  { memberSlug: "ldr", projectName: "SLife", projectYear: 2021, projectCategory: "ILLEGAL", structure: "Mafia Russe", grade: null, order: 0 },
  { memberSlug: "ldr", projectName: "American Dream", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Solntsevskaya", grade: null, order: 0 },
  { memberSlug: "charliie", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Commandant", order: 0 },
  { memberSlug: "charliie", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Juge", order: 0 },
  { memberSlug: "charliie", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "trilow", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Major", order: 0 },
  { memberSlug: "flox", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Capitaine", order: 0 },
  { memberSlug: "flox", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Agent de sécurité", order: 0 },
  { memberSlug: "flox", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "United States Marshals Service", grade: null, order: 0 },
  { memberSlug: "flox", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "flox", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "aydenbzz", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "aydenbzz", projectName: "SLife", projectYear: 2021, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "kanh", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Sergent-Chef", order: 0 },
  { memberSlug: "kanh", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "kanh", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "kanh", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "kanh", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "kanh", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "kanh", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Detective", order: 0 },
  { memberSlug: "aky", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Major", order: 0 },
  { memberSlug: "aky", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "aky", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "aky", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "aky", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: "Special Agent", order: 0 },
  { memberSlug: "aky", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "aky", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "aky", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "aky", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "aky", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "aky", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "aky", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "aky", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "veekoon", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Capitaine", order: 0 },
  { memberSlug: "veekoon", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "veekoon", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "alvaro", projectName: "iFive", projectYear: 2021, projectCategory: "LEGAL", structure: "iFive Police Department", grade: "Sergent-Chef", order: 0 },
  { memberSlug: "alvaro", projectName: "SLife", projectYear: 2021, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "babah-au-rhum", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "babah-au-rhum", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "babah-au-rhum", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Emissaire", order: 0 },
  { memberSlug: "babah-au-rhum", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Clan Genna", grade: "Membre", order: 0 },
  { memberSlug: "diablo", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: null, order: 0 },
  { memberSlug: "diablo", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "matador", projectName: "American Dream", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Commandant", order: 0 },
  { memberSlug: "matador", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "ILLEGAL", structure: "Famille Texane Ross", grade: "Membre", order: 0 },
  { memberSlug: "matador", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "matador", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Membre", order: 0 },
  { memberSlug: "matador", projectName: "SLife", projectYear: 2021, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "nalymu", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of Health", order: 0 },
  { memberSlug: "nalymu", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Diplomatic Security Service", grade: null, order: 0 },
  { memberSlug: "nalymu", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "okana", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "okana", projectName: "AMI RP", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "okana", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Sergeant", order: 0 },
  { memberSlug: "okana", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "okana", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "ILLEGAL", structure: "Famille Texane Ross", grade: "Fraterie Ross", order: 0 },
  { memberSlug: "okana", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "okana", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Brazo Derecho", order: 0 },
  { memberSlug: "okana", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Cayo Perico", grade: "Presidente", order: 0 },
  { memberSlug: "okana", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "okana", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "okana", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "okana", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "okana", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "okana", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "louisvrt", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sheriff", order: 0 },
  { memberSlug: "louisvrt", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "United States Marshals Service", grade: null, order: 0 },
  { memberSlug: "louisvrt", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "louisvrt", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: null, order: 0 },
  { memberSlug: "louisvrt", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "louisvrt", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "myoww", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy Sheriff", order: 0 },
  { memberSlug: "silexion", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "silexion", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "silexion", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "silexion", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Detective", order: 0 },
  { memberSlug: "silexion", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "silexion", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "wife", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: null, order: 0 },
  { memberSlug: "snow", projectName: "AMI RP", projectYear: 2023, projectCategory: "LEGAL", structure: "United States Marshals Service", grade: "Director", order: 0 },
  { memberSlug: "snow", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Assistant Chief Officer", order: 0 },
  { memberSlug: "snow", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Chief Operating Officer", order: 0 },
  { memberSlug: "snow", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "snow", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy Sheriff", order: 0 },
  { memberSlug: "snow", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Deputy Chief", order: 0 },
  { memberSlug: "snow", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "mowgli", projectName: "SunLight", projectYear: 2023, projectCategory: "ILLEGAL", structure: "Indépendants", grade: null, order: 0 },
  { memberSlug: "slight", projectName: "American Dream", projectYear: 2023, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "slight", projectName: "Anesya", projectYear: 2023, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "slight", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "slight", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Brazo Derecho", order: 0 },
  { memberSlug: "enzz-1313", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: null, order: 0 },
  { memberSlug: "enzz-1313", projectName: "ViceLand", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "rom1", projectName: "New Hill's V2", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel Madrazo", grade: null, order: 0 },
  { memberSlug: "rom1", projectName: "ViceLand", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "itd-leus", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Mafia Slave", grade: "Membre", order: 0 },
  { memberSlug: "itd-leus", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "itd-leus", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "itd-leus", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "itd-leus", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "itd-leus", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "itd-leus", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "itd-leus", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "itd-leus", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Detective", order: 0 },
  { memberSlug: "jamsheed", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Governor of San Andreas", order: 0 },
  { memberSlug: "jamsheed", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of Homeland Security", order: 0 },
  { memberSlug: "jamsheed", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Attorney", order: 0 },
  { memberSlug: "jamsheed", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "jamsheed", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "jamsheed", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Director", order: 0 },
  { memberSlug: "jamsheed", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Co-Directeur", order: 0 },
  { memberSlug: "jamsheed", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Co-Director", order: 0 },
  { memberSlug: "jamsheed", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Co-Directeur", order: 0 },
  { memberSlug: "jamsheed", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "jamsheed", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Captain", order: 0 },
  { memberSlug: "jamsheed", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Captain", order: 0 },
  { memberSlug: "jamsheed", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Commander", order: 0 },
  { memberSlug: "itzuno", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of State", order: 0 },
  { memberSlug: "itzuno", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "itzuno", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "itzuno", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "itzuno", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "itzuno", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "itzuno", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "itzuno", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "itzuno", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "itzuno", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "itzuno", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of State", order: 0 },
  { memberSlug: "m", projectName: "Wise", projectYear: 2024, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "m", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "nexley", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Fils du gouverneur", order: 0 },
  { memberSlug: "babah-au-rhum", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Fils du gouverneur", order: 0 },
  { memberSlug: "nexley", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Soldat du SD", order: 0 },
  { memberSlug: "jupipi", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Fils du gouverneur", order: 0 },
  { memberSlug: "jupipi", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "jupipi", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "killcot", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Senior Lead Officer", order: 0 },
  { memberSlug: "killcot", projectName: "GreenTown", projectYear: 2024, projectCategory: "LEGAL", structure: "Cayo Perico", grade: "Jefe de Servicios Secretos", order: 0 },
  { memberSlug: "killcot", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "killcot", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "killcot", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "killcot", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "faily", projectName: "GreenTown", projectYear: 2024, projectCategory: "ILLEGAL", structure: "Cartel de Cayo Perico", grade: "Jefe", order: 0 },
  { memberSlug: "faily", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "lukas44320", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "lukas44320", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "lukas44320", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "lukas44320", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "lukas44320", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "lukas44320", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "lukas44320", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "lukas44320", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "lea", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Agent spécial de Coordination", order: 0 },
  { memberSlug: "lea", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "lea", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "General Inspector", order: 0 },
  { memberSlug: "lea", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "lea", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "lea", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "pantoufle", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Attorney General", order: 0 },
  { memberSlug: "pantoufle", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Attorney General", order: 0 },
  { memberSlug: "pantoufle", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Co-Directeur", order: 0 },
  { memberSlug: "pantoufle", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "pantoufle", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "pantoufle", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Lieutenant", order: 0 },
  { memberSlug: "pantoufle", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Lieutenant", order: 0 },
  { memberSlug: "pantoufle", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Lieutenant", order: 0 },
  { memberSlug: "yns78", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "yns78", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Emissaire", order: 0 },
  { memberSlug: "zyrox-delta", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "zyrox-delta", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Chief Operating Officer", order: 0 },
  { memberSlug: "zyrox-delta", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "nadhino", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of State", order: 0 },
  { memberSlug: "nadhino", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Subtitute Attorney", order: 0 },
  { memberSlug: "nadhino", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "nadhino", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "nadhino", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "nadhino", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "nadhino", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Supervisor Special Agent", order: 0 },
  { memberSlug: "nadhino", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "nadhino", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "nadhino", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Sergeant", order: 0 },
  { memberSlug: "loumah", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: "Secretary of Culture", order: 0 },
  { memberSlug: "poqovitch", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: "Comissionner", order: 0 },
  { memberSlug: "poqovitch", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "poqovitch", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "3than94", projectName: "Projet X", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "3than94", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas Government", grade: null, order: 0 },
  { memberSlug: "3than94", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "3than94", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "3than94", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "3than94", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "3than94", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "3than94", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "3than94", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "titine", projectName: "OnlyRP", projectYear: 2025, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "100rancune", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "100rancune", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "100rancune", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "100rancune", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "enixo", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "enixo", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "enixo", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "mtdz", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "ILLEGAL", structure: "Famille Texane Ross", grade: null, order: 0 },
  { memberSlug: "mtdz", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "mtdz", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "mtdz", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "mtdz", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "mtdz", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "mtdz", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "vico", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "ILLEGAL", structure: "Famille Texane Ross", grade: null, order: 0 },
  { memberSlug: "jamsheed", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Attorney General", order: 0 },
  { memberSlug: "nadhino", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "LEGAL", structure: "Department of Justice", grade: "Juge", order: 0 },
  { memberSlug: "alix31", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: null, order: 0 },
  { memberSlug: "alix31", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "alix31", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "alix31", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "alix31", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "alix31", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "termiflux", projectName: "AriaLife V2", projectYear: 2026, projectCategory: "LEGAL", structure: "Internal Revenue Services", grade: null, order: 0 },
  { memberSlug: "termiflux", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "termiflux", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "termiflux", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "termiflux", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Deputy", order: 0 },
  { memberSlug: "termiflux", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "andrews", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "andrews", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "andrews", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Sergeant", order: 0 },
  { memberSlug: "jeanfilou", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "jeanfilou", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "jeanfilou", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "jeanfilou", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Sergeant", order: 0 },
  { memberSlug: "jeanfilou", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Sergeant", order: 0 },
  { memberSlug: "jeanfilou", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Sergeant", order: 0 },
  { memberSlug: "shin", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Special Agent", order: 0 },
  { memberSlug: "shin", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "shin", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "shin", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "sirius", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "sirius", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Rookie", order: 0 },
  { memberSlug: "sirius", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "sirius", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Rookie", order: 0 },
  { memberSlug: "chaixou", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "chaixou", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Rookie", order: 0 },
  { memberSlug: "chaixou", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "chaixou", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Rookie", order: 0 },
  { memberSlug: "le-k-ethan", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Rookie", order: 0 },
  { memberSlug: "le-k-ethan", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Trooper", order: 0 },
  { memberSlug: "le-k-ethan", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "tdoui05", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Rookie", order: 0 },
  { memberSlug: "tdoui05", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Rookie", order: 0 },
  { memberSlug: "tdoui05", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "reaper", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "United State Secret Service", grade: "Special Agent", order: 0 },
  { memberSlug: "reaper", projectName: "UltraRoleplay", projectYear: 2025, projectCategory: "LEGAL", structure: "Diplomatic Security Service", grade: "Special Agent", order: 0 },
  { memberSlug: "reaper", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Drug Enforcement Administration", grade: "Chief of Staff", order: 0 },
  { memberSlug: "reaper", projectName: "Ultraze", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Chief of Staff", order: 0 },
  { memberSlug: "reaper", projectName: "San Andreas Stories", projectYear: 2026, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Chief of Staff", order: 0 },
  { memberSlug: "reaper", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Deputy Director", order: 0 },
  { memberSlug: "reaper", projectName: "LegacyWorld", projectYear: 2026, projectCategory: "LEGAL", structure: "Milicia de Cayo Perico", grade: "Membre", order: 0 },
  { memberSlug: "reaper", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "Blaine County Sheriff Office", grade: "Assistant Chief", order: 0 },
  { memberSlug: "reaper", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Assistant Chief", order: 0 },
  { memberSlug: "reaper", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Assistant Chief", order: 0 },
  { memberSlug: "nael", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Police Officer", order: 0 },
  { memberSlug: "zimikio", projectName: "Dekay", projectYear: 2026, projectCategory: "LEGAL", structure: "Los Santos Police Department", grade: "Rookie", order: 0 },
  { memberSlug: "zimikio", projectName: "NoLimit", projectYear: 2026, projectCategory: "LEGAL", structure: "San Andreas State Police", grade: "Rookie", order: 0 },
  { memberSlug: "julie", projectName: "Arkane", projectYear: 2025, projectCategory: "LEGAL", structure: "Federal Bureau of Investigation", grade: "Special Agent", order: 0 },
  { memberSlug: "julie", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Bloods", grade: null, order: 0 },
  { memberSlug: "julie", projectName: "Arkane", projectYear: 2025, projectCategory: "ILLEGAL", structure: "Le Conseil (G-M)", grade: "Emissaire", order: 0 },
];
